routes/web.php
<?php

use App\Http\Controllers\AnalyticsController;
use App\Http\Controllers\AutomationController;
use App\Http\Controllers\Lists\LeedsController;
use App\Http\Controllers\MailingListController;
use App\Http\Controllers\TagsController;
use App\Http\Controllers\UserController;
use App\Models\MailingList;
use App\Models\Tag;
use App\Models\Trigger;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('dashboard');
    Route::resource('lists', MailingListController::class);
    Route::resource('lists.leeds', LeedsController::class);
    Route::resource('automation', AutomationController::class);;
    Route::resource('tags', TagsController::class);
    Route::get('user', [UserController::class, 'edit'])->name('user.edit');
    Route::patch('user', [UserController::class, 'update'])->name('user.update');
});

Route::post('an', [AnalyticsController::class, 'report'])->name('analytics.report');

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    protected $fillable = ['name', 'user_id'];

    use HasFactory;
}

app/Http/Controllers/TagsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Tag;
use Illuminate\Http\Request;

class TagsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tags = auth()->user()->tags()->orderBy('id', 'desc')->paginate();
        return view('tags.index', compact('tags'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tags.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string',
        ]);

        $tag = auth()->user()->tags()->create($request->only('name'));
        return redirect()->route('tags.index')->with('success', 'Dodano nowy tag!');
    }



    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tag = auth()->user()->tags()->where('id', $id)->firstOrFail();
        return view('tags.exit', compact('tag'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $tag = auth()->user()->tags()->where('id', $id)->firstOrFail();

        return redirect()->back()->with('success', 'Tag został zmieniony!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $tag = auth()->user()->tags()->where('id', $id)->firstOrFail();
        $tag->delete();
        return redirect()->route('tags.index')->with('success', 'Tag został usunięty!');
    }
}

resources/views/tags/create.blade.php
@extends('adminlte::page')

@section('title', 'Nowa lista leedów')

@section('content_header')
<h1>Nowa lista leedów</h1>
@stop

@section('content')
<div class="card">
    <div class="card-body">
        {{Form::open(['url'=>route('tags.store')])}}
        @include('tags.form')
        <button class="btn btn-primary">Zapisz</button>
        {{Form::close()}}
    </div>
</div>
@endsection

resources/views/tags/form.blade.php
<div class="row">
    <div class="col-md-6">
        <div class="form-group {{ $errors->has('name') ? 'has-error' : ''}}">
            {!! Form::label('name','Nazwa', ['class' => 'col-md-12']) !!}
            {!! Form::text('name', null, ['class' => 'form-control']) !!}
            {!! $errors->first('name', '<p class="help-block">:message</p>') !!}
        </div>
    </div>
</div>

resources/views/tags/index.blade.php
@extends('adminlte::page')

@section('title', 'Automatyzacje')

@section('content_header')
<h1>Lista schematów automatyzacji</h1>
@stop

@section('content')
<div class="card">
    <div class="card-body">

        <a href="{{route('tags.create')}}" class="btn btn-success btn-xs">Dodaj nowy tag</a>

        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nazwa</th>
                    <th>Akcje</th>
                </tr>

            </thead>
            <tbody>
                @foreach($tags as $tag)
                <tr>
                    <td>
                        {{$tag->id}}
                    </td>
                    <td>
                        {{$tag->name}}
                    </td>
                    <td>
                        {{Form::open(['method'=>'DELETE','url'=>route('tags.destroy',[$tag->id]),'class'=>'inline'])}}
                        <button class="btn btn-danger btn-xs"
                            onclick="return confirm('Jesteś pewien? Ta akcja może spowodować uruchomienie niektórych automatyzacji, które zawierają wyzwalacz lub warunek \'Usunięto tag\'')">Usuń</button>
                        {{Form::close()}}
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        <div class="row">
            <div class="col-md-12">
                {{$tags->links()}}
            </div>
        </div>

    </div>
</div>

@stop