routes/web.php
<?php

use App\Http\Controllers\AnalyticsController;
use App\Http\Controllers\AutomationController;
use App\Http\Controllers\Lists\LeedsController;
use App\Http\Controllers\MailingListController;
use App\Http\Controllers\TagsController;
use App\Http\Controllers\UserController;
use App\Models\MailingList;
use App\Models\Tag;
use App\Models\Trigger;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('dashboard');
    Route::resource('lists', MailingListController::class);
    Route::resource('lists.leeds', LeedsController::class);
    Route::resource('automation', AutomationController::class);;
    Route::resource('tags', TagsController::class);
    Route::get('user', [UserController::class, 'edit'])->name('user.edit');
    Route::patch('user', [UserController::class, 'update'])->name('user.update');
});

Route::post('an', [AnalyticsController::class, 'report'])->name('analytics.report');

app/Models/Leed.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Leed extends Model
{
    use HasFactory;

    protected $fillable = ['email', 'session', 'user_id', 'name', 'custom_field_1', 'custom_field_2', 'custom_field_3', 'custom_field_4'];



    public function lists()
    {
        return $this->belongsToMany(MailingList::class)->using(LeedMailingList::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    public function events()
    {
        return $this->hasMany(Event::class);
    }

    public function done_blocks()
    {
        return $this->hasMany(DoneBlock::class);
    }
}

app/Http/Controllers/Lists/LeedsController.php
<?php

namespace App\Http\Controllers\Lists;

use App\Http\Controllers\Controller;
use App\Models\Leed;
use Illuminate\Http\Request;

class LeedsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request, $id)
    {
        $perPage = $request->get('per_page', 25);
        $list = auth()->user()->lists()->where('id', $id)->firstOrFail();
        $leeds = $list->leeds()->orderBy('id', 'desc')->paginate($perPage);
        return view('lists.leeds.index', compact('list', 'leeds'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($id)
    {
        $list = auth()->user()->lists()->where('id', $id)->first();
        $tags = auth()->user()->tags;
        return view('lists.leeds.create', compact('list', 'tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $listId)
    {
        $this->validate($request, [
            'email' => 'nullable|email'
        ]);
        $data = $request->all();

        $list = auth()->user()->lists()->where('id', $listId)->first();
        $leed = auth()->user()->leeds()->create($data);
        $list->leeds()->attach($leed->id);
        $leed->tags()->sync($request->get('tags', []));

        return redirect()->route('lists.leeds.index', $list->id)->with('success', 'Kontakt dodany pomyślnie');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($list, $id)
    {
        $list = auth()->user()->lists()->where('id', $list)->firstOrFail();
        $leed = $list->leeds()->where('id', $id)->firstOrFail();
        $tags = auth()->user()->tags;

        return view('lists.leeds.edit', compact('list', 'leed', 'tags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $list, $id)
    {
        $this->validate($request, [
            'email' => 'nullable|email'
        ]);

        $list = auth()->user()->lists()->where('id', $list)->firstOrFail();
        $leed = $list->leeds()->where('id', $id)->firstOrFail();
        $leed->tags()->sync($request->get('tags', []));
        $leed->update($request->all());
        return redirect()->route('lists.leeds.index', $list->id)->with('success', 'Kontakt został zmieniony');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($list, $id)
    {
        $list = auth()->user()->lists()->where('id', $list)->firstOrFail();
        $leed = $list->leeds()->detach($id);
        return redirect()->route('lists.leeds.index', $list->id)->with('success', 'Kontakt został usunięty z tej listy');
    }
}

resources/views/lists/leeds/create.blade.php
@extends('adminlte::page')

@section('title', 'Dodaj nowy kontakt do listy "'.$list->name.'"')

@section('content_header')
<h1>Dodaj nowy kontakt do listy "{{$list->name}}"</h1>
@stop

@section('content')
<div class="card">
    <div class="card-body">
        {{Form::open(['url'=>route('lists.leeds.store',$list->id)])}}
        @include('lists.leeds.form')
        <button class="btn btn-primary">Zapisz</button>
        {{Form::close()}}
    </div>
</div>
@endsection

resources/views/lists/leeds/edit.blade.php
@extends('adminlte::page')

@section('title', 'Dodaj nowy kontakt do listy "'.$list->name.'"')

@section('content_header')
<h1>Dodaj nowy kontakt do listy "{{$list->name}}"</h1>
@stop

@section('content')
<div class="card">
    <div class="card-body">
        {{Form::model($leed,['method'=>'patch','url'=>route('lists.leeds.update',[$list->id,$leed->id])])}}
        @include('lists.leeds.form')
        <button class="btn btn-primary">Zapisz</button>
        {{Form::close()}}
    </div>
</div>
@endsection

resources/views/lists/leeds/form.blade.php
<div class="row">
    <div class="col-md-6">
        <div class="form-group {{ $errors->has('email') ? 'has-error' : ''}}">
            {!! Form::label('email','Adres email', ['class' => 'col-md-12']) !!}
            {!! Form::text('email', null, ['class' => 'form-control']) !!}
            {!! $errors->first('email', '<p class="help-block">:message</p>') !!}
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="form-group {{ $errors->has('name') ? 'has-error' : ''}}">
            {!! Form::label('name','Imię i nazwisko', ['class' => 'col-md-12']) !!}
            {!! Form::text('name', null, ['class' => 'form-control']) !!}
            {!! $errors->first('name', '<p class="help-block">:message</p>') !!}
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="form-group {{ $errors->has('tags') ? 'has-error' : ''}}">
            {!! Form::label('tags','Tagi', ['class' => 'col-md-12']) !!}
            {!! Form::select('tags[]', $tags->pluck('name','id'), null,
            ['multiple'=>true,'class' =>
            'form-control'])
            !!}
            {!! $errors->first('name', '<p class="help-block">:message</p>') !!}
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="form-group {{ $errors->has('custom_field_1') ? 'has-error' : ''}}">
            {!! Form::label('custom_field_1','Dodatkowe pole 1', ['class' => 'col-md-12']) !!}
            {!! Form::text('custom_field_1', null, ['class' => 'form-control']) !!}
            {!! $errors->first('custom_field_1', '<p class="help-block">:message</p>') !!}
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group {{ $errors->has('custom_field_2') ? 'has-error' : ''}}">
            {!! Form::label('custom_field_2','Dodatkowe pole 2', ['class' => 'col-md-12']) !!}
            {!! Form::text('custom_field_2', null, ['class' => 'form-control']) !!}
            {!! $errors->first('custom_field_2', '<p class="help-block">:message</p>') !!}
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="form-group {{ $errors->has('custom_field_3') ? 'has-error' : ''}}">
            {!! Form::label('custom_field_3','Dodatkowe pole 3', ['class' => 'col-md-12']) !!}
            {!! Form::text('custom_field_3', null, ['class' => 'form-control']) !!}
            {!! $errors->first('custom_field_3', '<p class="help-block">:message</p>') !!}
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group {{ $errors->has('custom_field_4') ? 'has-error' : ''}}">
            {!! Form::label('custom_field_4','Dodatkowe pole 4', ['class' => 'col-md-12']) !!}
            {!! Form::text('custom_field_4', null, ['class' => 'form-control']) !!}
            {!! $errors->first('custom_field_4', '<p class="help-block">:message</p>') !!}
        </div>
    </div>
</div>

resources/views/lists/leeds/index.blade.php
@extends('adminlte::page')

@section('title', 'Lista mailingowa "'.$list->name.'"')

@section('content_header')
<h1>Lista mailingowa "{{$list->name}}"</h1>
@stop

@section('content')
<div class="card">
    <div class="card-body">
        <div class="col-md-12 text-right mb-2">
            {{Form::open(['url'=>route('lists.destroy',$list->id),'method'=>"DELETE"])}}
            <a href="{{route('lists.leeds.create',$list->id)}}" class="btn btn-success">Dodaj nowy kontakt</a>
            <button onclick="return confirm('Jesteś pewien?')" class="btn btn-danger">Usuń tę listę</button>
            {{Form::close()}}
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th>Email</th>
                    <th>Imię i nazwisko</th>
                    <th>Dodatkowe pole 1</th>
                    <th>Dodatkowe pole 2</th>
                    <th>Dodatkowe pole 3</th>
                    <th>Dodatkowe pole 4</th>
                    <th>Tagi</th>
                    <th>Akcje</th>
                </tr>

            </thead>
            <tbody>
                @foreach($leeds as $leed)
                <tr>
                    <td>
                        {{$leed->email}}
                    </td>
                    <td>
                        {{$leed->name}}
                    </td>
                    <td>
                        {{$leed->custom_field_1}}
                    </td>
                    <td>
                        {{$leed->custom_field_2}}
                    </td>
                    <td>
                        {{$leed->custom_field_3}}
                    </td>
                    <td>
                        {{$leed->custom_field_4}}
                    </td>

                    <td>
                        @foreach($leed->tags as $tag)
                        <span class="badge bg-success">{{$tag->name}}</span>
                        @endforeach
                    </td>
                    <td>
                        <a href="{{route('lists.leeds.edit',[$list->id,$leed->id])}}"
                            class="btn btn-xs btn-primary">Edytuj</a>
                        {{Form::open(['method'=>'DELETE','url'=>route('lists.leeds.destroy',[$list->id,$leed->id]),'class'=>'inline'])}}
                        <button class="btn btn-danger btn-xs" onclick="return confirm('Jesteś pewien?')">Usuń</button>
                        {{Form::close()}}
                    </td>

                </tr>
                @endforeach
            </tbody>
        </table>
        <div class="row">
            <div class="col-md-12">
                {{$leeds->links()}}
            </div>
        </div>

    </div>
</div>

@stop